#backend.yaml

apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: helm
type: Opaque
data:
  MYSQL_ROOT_USERNAME: cm9vdA==
  MYSQL_ROOT_PASSWORD: MTIzNDU2
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: helm
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql-service:3306/testdb?useSSL=false&allowPublicKeyRetrieval=true&allowEmptyPassword=yes&createDatabaseIfNotExist=true&autoReconnect=true
  SPRING_DATASOURCE_USERNAME: root

---
---
# Backend Service
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: helm
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP

---
# Backend Deployment


apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: helm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: aymennf/bimg2:latest
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_USERNAME
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: SPRING_DATASOURCE_USERNAME
